config/routes.rb
Rails.application.routes.draw do
  get 'calendar/show'

  devise_for :users
  root "welcome#index"
  resource :calendar, only: [:show], controller: :calendar
  resources :events, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed

  validates :username, uniqueness: true
  validates :username, presence: true

  validates :email, uniqueness: true
  validates :email, presence: true

  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username, :avatar, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :username, :avatar, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :username, :avatar, :password, :password_confirmation])
  end

  def after_sign_in_path_for(resource)
    calendar_path
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def show
    @events_by_date = Event.all.group_by(&:date)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
    @friends = current_user.active_relationships.map { |r| r.followed }
  end

  def create
    @event = Event.new(name: event_params[:name])
    @event.date = Chronic.parse(event_params[:date]).utc.midnight
    @event.start_time = event_params[:start_time]
    @event.end_time = event_params[:end_time]
    @event.description = event_params[:description]
    if @event.save
      redirect_to calendar_path, notice: "Event #{@event.name} created"
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params["id"])
  end


  private
  def event_params
    params.require(:event).permit([:date, :name, :start_time, :end_time, :description])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
require 'calendar'

module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/calendar/show.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">
      <%= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-backward"></i>
      <% end %>
      <%= "#{@date.strftime("%B")} #{@date.year}" %>
      <%= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-forward"></i>
      <% end %>
      <%= link_to new_event_path, class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-plus"></i>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= calendar @date do |date| %>
      <%= date.day %>
      <% if @events_by_date[date.midnight] %>
        <ul>
          <% @events_by_date[date.midnight].each do |event| %>
            <li><%= link_to event.name, event_path(event.id) %></li>
          <% end %>
        </ul>
      <% end %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<%= form_for @event, html: { role: 'form' } do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.text_field :date, data:{ provide:'datepicker' }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :start_time %>
    <%= form.text_field :start_time, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :end_time %>
    <%= form.text_field :end_time, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <%= form.label "Invite your friends" %>
  <div class="friends">
    <% @friends.each_with_index do |friend, index|  %>
      <div class="friend" id="friend-<%= index %>">
        <%= image_tag friend.avatar , height: '100px', alt: friend.username %>
        <p><%= friend.username %></p>
      </div>
    <% end %>
  </div>

  <div class="clearfix"></div>

  <br />
  <br />

  <div class="">
    <%= form.submit "Create Event!", class: 'btn btn-primary btn-block' %>
  </div>

<% end %>


<script>
  $( function() {
    $( "#event_date" ).datepicker();
  } );

  $('.friend').click(function() {
    $('#' + this.id).toggleClass('invite-friend')
  });
</script>

app/views/events/show.html.erb
<div class="panel panel-default">
  <div class="container">
    <h2><%= @event.name %></h2>
    <p>on <%= @event.date.strftime("%B %d, %Y") %></p>
    <% if @event.start_time.present? %>
      <p>from <%= @event.start_time %></p>
    <% end %>
    <% if @event.start_time.present? && @event.end_time.present? %>
      <p>to <%= @event.end_time %></p>
    <% end %>
    <br>
    <p><%= @event.description %></p>
    <h3>Friends: </h3>
    <table>
      <tr>
        <th>Friend</th>
        <th>Parent said yes?</th>
      </tr>
      <tr>
        <td><%= image_tag 'girl-12.png', height: '100px' %></td>
        <td>Yes</td>
      </tr>
      <tr>
        <td><%= image_tag 'girl-1.png', height: '100px' %></td>
        <td>Yes</td>
      </tr>
      <tr>
        <td><%= image_tag 'girl-3.png', height: '100px' %></td>
        <td>No</td>
      </tr>
      <tr>
        <td><%= image_tag 'girl-4.png', height: '100px' %></td>
        <td>No</td>
      </tr>
      <tr>
        <td><%= image_tag 'girl-5.png', height: '100px' %></td>
        <td>No</td>
      </tr>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlaySpace</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Architects+Daughter|Bungee|Caveat|Chewy|Indie+Flower|Shadows+Into+Light+Two" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
  </head>

  <body>

    <!-- Fixed navbar -->
  <nav class="navbar navbar-default navbar-custom">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#"><%= image_tag 'playspace-logo.png', height: '50px' %></a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to 'Calendar', calendar_path, class: 'btn yellow-btn bold-btn navb-button'  %></li>
            <li><%= link_to 'Account', edit_user_registration_path, class: 'btn yellow-btn bold-btn navb-button'  %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn yellow-btn bold-btn navb-button' %></li>
          <% else %>
            <li><%= link_to 'Create An Account', new_user_registration_path, class: 'btn yellow-btn bold-btn navb-button'  %></li>
            <li><%= link_to 'Sign In', new_user_session_path, class: 'btn yellow-btn bold-btn navb-button'  %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>


    <div class="container">
      <% if notice.present? %>
        <div class="panel panel-success">
          <div class="panel-heading">
            Notice
          </div>
          <div class="panel-body">
            <%= notice %>
          </div>
        </div>
      <% end %>
      <% if alert %>
        <div class="panel panel-danger">
          <div class="panel-heading">
            Notice
          </div>
          <div class="panel-body">
            <%= alert %>
          </div>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <footer class="footer">
      <div class="container">
        <p>some text here</p>
      </div>
    </footer>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron vertical-center">
  <h1>PlaySpace</h1>
</div>